name: prova_seventh
description: Projeto para a prova da Seventh

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  build_runner: ^2.4.7
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/